# Generated by Django 2.0.3 on 2019-08-20 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20190820_1910'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='upadted',
            new_name='updated',
        ),
    ]
