# Generated by Django 2.0.3 on 2019-08-23 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20190820_1916'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='image',
            new_name='artcle_image',
        ),
    ]
