# Generated by Django 2.0.3 on 2019-08-23 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20190823_1750'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='tag',
            new_name='article_type',
        ),
        migrations.RemoveField(
            model_name='article',
            name='type',
        ),
    ]
