# Generated by Django 2.0.3 on 2019-09-01 14:34

from django.db import migrations, models
import django.utils.timezone
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20190823_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='data',
            field=froala_editor.fields.FroalaField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='created',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='updated',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
