# Generated by Django 2.0.3 on 2019-09-14 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20190901_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.SlugField(default='abc', unique=True),
        ),
    ]
